### PR TITLE
API Org App - Jhommark Macasaet

### PR DESCRIPTION
**Pull request by jhommark**
To run the application, open your terminal, cd on the source code directory and do a '**bower install && npm install**'. After all the packages have been installed, you may now enter '**npm start**' in the terminal.

Since I used AngularJS in the application, the design pattern used is **Model-View-ViewModel (MVVM)** which facilitates a separation of development of the GUI from development of the business logic or back-end logic.
While using the design pattern, I also followed a nice code styling guide by John Papa who is a Google Developer Expert and Microsoft Regional Director. It implements the good practices based on his development experience with Angular and working in teams. It is very helpful for developers to write codes wich can be easily maintained.

The libraries and frameworks that I used are **AngularJS 1, Loopback Framework v2 (Node.js), and Bootstrap 3**.

I used AngularJS 1 since it is currently the front-end framework that I am most comfortable with, although I can also use the more recent version of it which is 2 and the most recent which is 4, but still I decided to choose the one where I am more comfortable with so I can develop the application with ease. For the back-end, I used Loopback framework v2 which is powered by Node.js. I chose to use it because I can easily create dynamic end-to-end (E2E) REST APIs with it. It has many tools like easy-to-use CLI wizard, built-in API Explorer and many more. It can easily generate API endpoints after creating your own models. For the user interface, I used Bootstrap 3 which is the most popular HTML, CSS and JS framework for developing responsive websites or web applications. I chose it so I can easily develop the interfaces without creating my own stylesheets and I am already comfortable of using it.

While making the app, there are major challenges that I encountered like in time and decision making. Time because I am currently employed and busy on my tasks and deadlines, I prioritize them but still I can manage to grab time and make this. Decision making because at first I was unsure of what am I going to use, whether AngularJS 1, 2 or 4. But since I am more experienced with AngularJS 1 and already comfortable with it, I chose it.

If I had more time, I would improve the design of the interfaces. Another one is to use the most recent version of AngularJS, this would also be a good time or opportunity for me to practice coding with the latest web technologies.

### CODE REVIEW

**Comment by zakame** [comment]
You applied previously, right? https://github.com/yoyo-holdings/api-org-app/pull/8

**Comment by jhommark** [comment]
Yes, I guess it was 8 months ago and I'm trying my luck for this time. If you still allow it, then I'll still push.

**Comment by zakame** [comment]
Considering this PR has nearly the same code as #8 (but seems the forked repo isn't there anymore) it is ok.  Though I expected that tech-wise, you have made some upgrades since last year.

**Comment by jhommark** [comment]
Well, yes, I was about to use Angular 2 or 4 instead. Actually, I have started coding with it but since time is running while I'm busy with other priorities in my current job, I decided to reuse my previous work and just improve some flaws in the codes.

**Comment by zakame** [comment]
Great!  Please do make updates as you see fit.

**Pull request closed without merging**
