### PR TITLE
Yoyo application

### PR DESCRIPTION
**Pull request by rrcc0044**
DISCLAIMER: the intructions to run the app is inside _docs/index.html_

What design patterns did you use inside the application?
- for backend Phoenix follows Model-View-Controller pattern, for frontend I used Component-based Pattern.

What libraries did you use?
- **VueJs** data-driven uis, fast, I really prefer templating and easy to learn. There is React but I prefer Vue because of intuitiveness and its pretty straight-forward
- **MomentJs** for date formatting
- **VueResource** as HTTP client
- **VeeValidate** for form validation
- **VueRouter** for routing
- **Bulma** for styling, based on flexbox and it has everything I need. Preferred bulma over bootstrap because its based on flexbox but I can use both.
- **FontAwesome** for rendering awesome fonts

What major challenges did you encounter when making the app?
- Tying things up (connecting both apps), rendering UI's because Bulma doesnt provide behaviors for the elements unlike Bootstrap and the temptation of the outside world because of the long weekend :smile: 

If you had more time, what additional features would you like to add?
Authentication then csrf protection. a public wall where anybody can add notes that gets updated in realtime using long polling. Draggable todos you can drag it in a div element to complete the todo.

### CODE REVIEW

**Comment by htgc** [comment]
Thank you for your PR @cl0ud9 !
Let me ask some questions.

1. How long have you coded Elixir/Phoenix?
2. How long did you take to code for this PR?
3. What is strength of Elixir compare to other language?
4. Which side do you prefer either frontend or backend?

**Comment by cl0ud9** [comment]
Hi @htgc !
1. I was introduced to functional programming using elixir this year and was hooked in this new paradigm.
2. 4 days
3. Elixir leverages todays computing. cpu arent getting any faster instead more cores are being added into it which means modern softwares need to use as many cores as possible to maximize the use of the machine. and with that Elixir is built with concurrency in mind and is powered by a 20year old Erlang-VM which is used for building fault-tolerant softwares.
4. Im leaning towards backend but currently Im doing both

**Comment by htgc** [comment]
Thanks! I agree Erlang is suitable for multi core programing although I'm worried we mightn't give chance to code Elixir/Erlang for our project immediately :)

**Comment by cl0ud9** [comment]
I agree, it isnt mature enough but it really boils down to the use case :)

**Pull request closed without merging**
