### PR TITLE
Created the notetaking app

### PR DESCRIPTION
**Pull request by aindong**
- What design patterns did you use inside the application?
-- MVC
-- Decorator
-- Honestly most of this are actually already built on django

- What libraries did you use?
-- Django
-- Django Rest Framework
-- ReactJS
-- Antd

- Why did you use this library?
-- DRF: Almost all of the needed things to create a restful api is already built inside, I enjoy learning how to build something from scratch but I also want to utilize tools that are already there
-- Django: I am aware that there are micro frameworks out there that is good for building small Restful apis, but I am fascinated how to create things on django. 
-- React: I found react very intuitive and expressive, it is fast, easy to learn and get things done. I may be bias about react, I've used it for around 1 - 2 years now for all the frontend that I am building and I am happy with how react is. I believe it's not about the js framework(there's a bunch of them already) it's the experience and how happy, you are in a technology.

- Are there other libraries available?
-- Yes
-if yes, what made you choose this library over the others?
-- There are actually a bunch of alternatives out there, and I can't really compare them because it would make me look bias, there are use cases where everyone of them is best suited for and it's not really about the technology, it's about the developer, is he happy? is he productive on that? Then its all good.

- What major challenges did you encounter when making the app?
-- I've never built a web service/web app on django before, learning is one of the challenges and looking for well maintained libraries that are not dead, fortunately, the python community is very active and almost everything that I've stumbled into are active
  - If you had more time, what additional features would you like to
    add?
-- I'd like to have some analytics how fast or how often a TODO is being marked as DONE
-- Add a search functionality on the todo
-- Make this multi-tenant or account base, so different users will have different todos
-- Add share to social media (Y'know everyone is sharing their data nowadays)

  In addition, you may provide more information in your PR/patch email
  that you would like us to know.

- I've setup a simple docker-compose for easily deploying this app into other machines
- Also provided a Makefile (I know this is old school already but its still helpful)

# Running the app
- First, you should have a docker installed on your machines
- clone the repository
- go to the cloned repository
- run `make build` and wait for the docker images/container to be built
- after building the containers, run them using `make up`
- you can access the application frontend on `http://localhost:3000` and the api on `http://localhost:8000`

### CODE REVIEW

**Comment by rrcc0044** [comment]
Hi @aindong! thank you for taking the time to do this exercise. However after successfully building the image and container, Im having a bad gateway error after visiting `http://localhost:3000`

**Comment by aindong** [comment]
hi @rrcc0044 thanks for that, it seems yarn is not installing the packages correctly, please try to `make build` again.

**Comment by aindong** [comment]
Hi @htgc  yeah I forgot to change that! my bad, the service.js actually came from the projects I've built using laravel and ruby before, I mostly use `message` for the object!

The frontend took more time since I think I over-engineered it, I implemented redux and redux-saga which I think is not really required to be able to produce the same result.

The Backend took me around less than a day, since most Rest/API operations are already provided by the Django Rest Framework (Serializing, routing, documentation, views)

**Comment by htgc** [comment]
noted. thanks!

**Pull request closed without merging**
